# -*- mode:python -*-

Import('*')

DebugFlag('DmaUnit')
DebugFlag('MegaCmdQueue')
DebugFlag('SpecializedExecutionUnit')
DebugFlag('ScratchpadMemory')

SimObject('DmaUnit.py', sim_objects=['DmaUnit'])
SimObject('MegaCmdQueue.py', sim_objects=['MegaCmdQueue'])
SimObject('SpecializedExecutionUnit.py',
          sim_objects=['SpecializedExecutionUnit'])
SimObject('ScratchpadMemory.py', sim_objects=['ScratchpadMemory'])
Source('DmaUnit.cc')
Source('MegaCmdQueue.cc')
Source('SpecializedExecutionUnit.cc')
Source('ScratchpadMemory.cc')
