# -*- mode:python -*-

Import('*')

DebugFlag('MegaCmdQueue')
DebugFlag('SpecializedExecutionUnit')
DebugFlag('DmaUnit')
DebugFlag('MpuUnit')
DebugFlag('ScratchpadMemory')

SimObject('MegaCmdQueue.py', sim_objects=['MegaCmdQueue'])
SimObject('DmaUnit.py', sim_objects=['DmaUnit'])
SimObject('MpuUnit.py', sim_objects=['MpuUnit'])
SimObject('SpecializedExecutionUnit.py',
          sim_objects=['SpecializedExecutionUnit'])
SimObject('ScratchpadMemory.py', sim_objects=['ScratchpadMemory'])
Source('MegaCmdQueue.cc')
Source('DmaUnit.cc')
Source('MpuUnit.cc')
Source('SpecializedExecutionUnit.cc')
Source('ScratchpadMemory.cc')
